"id","question","optionone","optiontwo","optionthree","optionfour","answer"
1,"Father of JAVA -","James Gosling","James","Ponting","Adam","James Gosling"
2,"Number of primitive data types in java -","2","6","5","7","8"
3,"select valid statement-","char[] ch = new char()","char[] ch = new char(5)","char[] ch = new char[]","char[] ch = new char[5]","char[] ch = new char[5]"
4,"Array in java are -","Object Reference","Object ","Reference type","value","Object"
5,"Who developed object-oriented programming","Adele Goldberg","Dennis Ritchie ","Alan Kay "," Kay","Alan Kay"
6,"Automatic type conversion is possible in which of the possible cases-","Byte to int","Int to long","Long to int","Short to int","Int to long"
7,"When an array is passed to a method, what does the method receive?","Copy of first element","length of the array","The reference of the array","copy of the array ","The reference of the array"
8,"What is the extension of java code files?"," .js",".txt",".class",".java",".java"
11,"Which of these cannot be used for a variable name in Java?","identifier ","identifier & keyword","keyword","none of the mentioned","keyword"
